### ISSUE TITLE
local - Docker-compose failed 

### ISSUE THREAD

**Issue by fenix011** [emanchado/narrows#28] opened 2021-03-25 20:54 UTC
When local - Docker-composing , i'm getting  
`
...
jordi@anarres:~/Docker/narrows> docker-compose create && docker-compose up -d
...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN narrows@0.0.1 No repository field.
npm WARN narrows@0.0.1 license should be a valid SPDX license expression
npm ERR! Linux 5.11.4-1-default
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@5.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the bcrypt@5.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/narrows/npm-debug.log
ERROR: Service 'narrows' failed to build : The command '/bin/sh -c npm install && npm install -g elm@0.18 && npm install -g pm2 && elm-package install --yes && npm run build' returned a non-zero code: 1
`

( on openSUSE Tumbleweed with latest  dokcker/ NodeJS running fine with other projects...)

what am i missing ?

**Comment by emanchado** [comment] 2021-03-26 14:41
Hm, apparently nothing, because I can reproduce locally. I don't use Docker myself, and I know very little about it. The Dockerfile was an external contribution (I should have probably marked it as such).

I'll have a look and will try to figure it out, but if you have any pointers or ideas, or find out anything, please post here!

**Comment by emanchado** [comment] 2021-03-26 21:13
Can you try with the [docker-updates](https://github.com/emanchado/narrows/tree/docker-updates) branch and tell me if it works? If it does I'll merge it to master and close this 😄

As it turns out, there were several things out of date in the installation instructions, including the `Dockerfile`.

**Comment by emanchado** [comment] 2021-07-07 19:52
Not received any updates or info, so I'm going to assume that my fix is enough. At the very least it's an improvement.

**Closed** 2024-10-21 14:50 UTC
